language: java

jdk:
  - oraclejdk8
  - oraclejdk7

  before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y byacc

  before_script:
    - mkdir -p build dist doc
    # Get the latest fregec.jar to compile the compiler
    - curl -L -o fregec.jar https://github.com/Frege/frege/releases/download/3.22.324/frege3.22.367-g2737683.jar

  script:
    - make runtime
    - make compiler1 || make compiler1 || true   # until issue#100 is fixed
    # make compiler2 || make compiler2 || true   # until issue#100 is fixed
    # make compiler  || make compiler  || true   # until issue#100 is fixed
    # make fregec.jar dist && java -cp fregec.jar frege.tools.Quick -v fregec.jar
